name: 'Require Given Push is to a PR'
description: 'Requires that the current push commit is to an open PR branch. If not, action will fail.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
